# Generated by Django 4.2.4 on 2023-08-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sara', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addapplication',
            name='name',
        ),
        migrations.AddField(
            model_name='addapplication',
            name='applink',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='App Link'),
        ),
        migrations.AddField(
            model_name='addapplication',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='addapplication',
            name='mobile',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='addapplication',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='WhatsApp'),
        ),
    ]
